### PR TITLE
Add injecting of private class fields into patching methods

### PR DESCRIPTION
**Pull request by sirhamsteralot**
- Add automatic injecting of private class fields into patching methods by their parameter name, To inject prefix a parameter in the patching method with  \_\_field\_

Code by equinox™ testing underway.

--ps there is only one file changed despite the 5 commits, probably should make them into one commit.

### CODE REVIEW

**Comment by Equinox-** [comment]
Fix your formatting

**Comment by rexxar-tc** [comment]
Anyone built a test case for this yet?

**Comment by sirhamsteralot** [comment]
I'm just going to do this now, if i can get torch to build i will test it with a little test plugin aswell.

**Comment by sirhamsteralot** [comment]
Tested by Prefixing UpdateMassFromInventories and changing a gridname in m_grid to check later if all grids were changed.
Test Code:
https://imgur.com/plu82W9
Results:
https://imgur.com/HwfE1y6
After a while nothing gets renamed anymore because everything has been successfully renamed and so the field got properly injected. The results were also successfull without using the argument with ref:
https://imgur.com/qPwUAfC

To test it working with statics m_removalResults was accessed and the size of the list was output:
https://imgur.com/7GkBakB
Result, only after manually removing a block on a grid:
https://imgur.com/QJe7amP
This shows its not null and the correct values are actually being inserted.

(these are terrible tests i know but at least it shows that the feature is now working).

**Pull request merged**
